### ISSUE TITLE
login form doesn't recognise password array key

### ISSUE THREAD

**Issue by Tashfinz** [daveh/php-signup-login#2]
Hi Dave I've gotten stuck and I don't know how to overcome this after trying for some time now. 
The form is sending data to my user table with the signup being successful the issue is the login form doesn't work due to the password array key not being identified.

Warning: Undefined array key "password" in C:\xampp\htdocs\login-form\login.php on line 17
 16           if ($user) {
 17               if (password_verify($_POST["password"], $user["password_hash"])) {
 18                  die("Login Successful");
 19              }
 20          }

the repository is below. 
https://github.com/Tashfinz/signup

**Comment by daveh** [comment]
Your password input is missing the name attribute, which is what is used to identify it in the `$_POST` array. So instead of this:

`<input type="password">`

it should be this:

`<input type="password" name="password">`

**Comment by Tashfinz** [comment]
Thank you very much. I tried commenting on YouTube...however my comment wouldn't post for some reason?
