### ISSUE TITLE
JustValidate doesn't work

### ISSUE THREAD

**Issue by Tashfinz** [daveh/php-signup-login#3]
Hi Daveh, 

I was following your login video and I found that not only could I not get the JustValidate to work on my own project, but it came to my attention after downloading this repo it doesn't appear to work as demonstrated in the video 36:20 . Is there perhaps any refactoring that needs be done to get this to work as intended for frontend validation?

https://www.youtube.com/watch?v=5L9UhOnuos0&list=WL&index=7&t=2142s&ab_channel=DaveHollingworth

**Comment by daveh** [comment]
It works for me - what exactly is the problem? I would check the browser's web developer tools to see if there are any network issues for example

**Comment by Tashfinz** [comment]
it appears there's a 404 error with the validation.js file. So the php validation does work, however the just validate library doesn't appear to work with 404 error  i see displayed on my console [error code](https://i.imgur.com/hZcb7TR.png)

**Comment by daveh** [comment]
It looks like your code is in a subfolder of the web server root - so you need to include that in the URL for the JavaScript code:

`<script src="/php-signup-login-main/js/validation.js" defer></script>`

**Comment by Tashfinz** [comment]
Thank you very much it works now. I greatly appreciate your help thank you very much daveh.
