### ISSUE TITLE
Fatal error: Uncaught mysqli_sql_exception: Duplicate entry 'GMAIL@gmail.com' for key 'email'

### ISSUE THREAD

**Issue by Th0ngpv** [daveh/php-signup-login#5]
Fatal error: Uncaught mysqli_sql_exception: Duplicate entry 'GMAIL@gmail.com' for key 'email' in C:\xampp\htdocs\php-signup-login\process-signup.php:45 Stack trace: #0 C:\xampp\htdocs\php-signup-login\process-signup.php(45): mysqli_stmt->execute() #1 {main} thrown in C:\xampp\htdocs\php-signup-login\process-signup.php on line 45

I keep getting this error and don't know what to do .

**Comment by daveh** [comment]
If you have a unique index on the email column, you'll get this error if you try and insert a new value - what code do you have for catching the duplicate index error?

**Comment by poetaetoh** [comment]
Try this. Instead of for example

```
if ($stmt->execute()) {

    header("Location: signup-success.html");
    exit;
    
} else {
    
    if ($mysqli->errno === 1062) {
        die("email already taken");
    } else {
        die($mysqli->error . " " . $mysqli->errno);
    }
}
```

Change the structure into something like

```
try
    {
      $stmt->execute();
      header("Location: signup-success.html");
      exit;
    }
catch(Throwable $e)
    {
      echo $e;
      if ($mysqli->errno === 1062) {
        echo "email already taken";
          } else {
              echo "$mysqli->error $mysqli->errno";
          }
    }
```
Hope it helps.

**Comment by Th0ngpv** [comment]
add this line of code before check for email

mysqli_report(MYSQLI_REPORT_OFF);
