### ISSUE TITLE
issue with password validation

### ISSUE THREAD

**Issue by ljara2106** [daveh/php-signup-login#6]
on signup page
the password validation is not working - browser debugger throws following error

Uncaught TypeError: Cannot read properties of undefined (reading 'em')
    at Object.validator (validation.js:40:54)
    at Object.validateFieldRule (just-validate.production.min.js:1:13737)
    at just-validate.production.min.js:1:14463
    at Array.forEach (<anonymous>)
    at Object.validateField (just-validate.production.min.js:1:14437)
    at Object.handleFieldChange (just-validate.production.min.js:1:4444)
    at HTMLInputElement.<anonymous> (just-validate.production.min.js:1:4713)

**Comment by daveh** [comment]
Check the `id` attribute of the element you're trying to access from the script matches what you're specifying

**Comment by ljara2106** [comment]
> Check the `id` attribute of the element you're trying to access from the script matches what you're specifying

im just using your whole code and your HTML - not sure why your code is throwing that error. the id looks ok.

**Comment by daveh** [comment]
It works for me - check the network tab in your web browser dev tools to make sure there is no error loading the script files - other than that, it's a bit difficult to debug without being able to reproduce the error - try inserting debugging statements in various places, see if you can track down which line of code is causing the problem.

**Comment by ljara2106** [comment]
i got it working correctly by fixing the .addfield password confirmation section to:


.addField("#password_confirmation", [
        {
            validator: (value) => {
                const passwordValue = document.querySelector("#password").value;
                return value === passwordValue;
            },
            errorMessage: "Passwords should match"
        }
    ])
